Retention Reports
Sage-Bionetworks/BridgeWorkerPlatform pull request #77
Opened 2019-08-19 21:21 UTC by janaechan

2019-08-19 21:40 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/reporter/helper/BridgeHelper.java
> +    public Map<RequestInfo, ActivityEventList> getActivityEventForParticipant (String studyId, List<StudyParticipant> participants)
I would key this map by something like user ID. I'm not 100% sure that two RequestInfo objects generated by the Swagger codegen libraries won't have the same hashCode (value equality). User ID is guaranteed to be unique per user.

2019-08-19 21:40 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/reporter/helper/BridgeHelper.java
> +    }
This looks like test data in the BridgeHelper. This should be moved to a test class only in the test class path.

2019-08-19 21:40 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/reporter/helper/BridgeHelper.java
> +    }
Same. This looks like test data, it should be under src/test not src/main.

2019-08-19 21:40 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/reporter/request/ReportType.java
> +	DAILY_RETENTION("DAILY_RETENTION");
Replace tab with four spaces. Four spaces per indentation level is the standard for all Bridge java code.

2019-08-19 21:40 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +        List<StudyParticipant> participants = bridgeHelper.getParticipantsForStudy(studyId, startDate, endDate);
I'm a little worried about loading all participants and their request info objects or a study with many users, like Cardiovascular, which has 63,000 users. Iterating through the users and processing each in turn might be better.

2019-08-19 21:40 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +        		System.out.println("Created on: " + entry.getKey().getCreatedOn().toLocalDate() + " Signed in on: " + entry.getValue().getSignedInOn().toLocalDate());
Remove sop statements in your final code. :-)

2019-08-19 22:06 UTC, DwayneJengSage requested changes

2019-08-19 22:06 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +        Map<StudyParticipant, RequestInfo> requestInfos = bridgeHelper.getRequestInfoForParticipant(studyId, participants);
I wouldn't recommend using a mutable object as a hash key. It's really easy to accidentally modify the hash key, and then suddenly your entry disappears from the hashtable.

I'd recommend instead creating a map from String to RequestInfo, where the key is StudyParticipant.getId().

You'd also need to create a second map from String to StudyParticipant. Guava Maps.uniqueIndex https://guava.dev/releases/snapshot/api/docs/com/google/common/collect/Maps.html#uniqueIndex-java.lang.Iterable-com.google.common.base.Function- should be able to do this for you.

```
Maps.uniqueIndex(participants, StudyParticipant::getId);
```

2019-08-19 22:06 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +            	}
Looks like there's mixed tabs and spaces here. I'd recommend double checking Eclipse's code style settings and making sure we're converting tabs into 4 spaces and using 4-space indent.

2019-08-19 22:06 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +        Map<RequestInfo, ActivityEventList> activityEventList = bridgeHelper.getActivityEventForParticipant(studyId, participants);
Similarly, you'll want to map participant ID to ActivityEventList. Plus, there's no reason to load RequestInfo a second time since we already have a map of RequestInfos.

2019-08-19 22:06 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +    	    			int days = Days.daysBetween(entry.getValue().getItems().get(i).getTimestamp().toDateTime().toLocalDate(), entry.getKey().getUploadedOn().toLocalDate()).getDays();
These are some very long lines. I'd recommend setting a max line width to 120 characters to make the code easier to read. IntelliJ helpfully shows a purple line (color configurable) where 120 characters is. I dunno if Eclipse has a similar setting.

2019-08-19 22:06 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +    	    			int days = Days.daysBetween(entry.getValue().getItems().get(i).getTimestamp().toDateTime().toLocalDate(), entry.getKey().getUploadedOn().toLocalDate()).getDays();
There seems to be some inconsistency here. You check if RequestInfo.getSignedInOn() is null, but you actually use getUploadedOn. Also, for bySignIn, you index to participant.getCreatedOn(), but here you index to activities_retrieved. These should probably use the same index for consistency.

2019-08-19 22:06 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +        		}
A participant only has one activities_retrieved event. Once you find it, you should break out of the loop.

2019-08-19 22:06 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +        String reportId = scheduler + scheduleType.getSuffix();
I know this is the same pattern we use elsewhere, but I don't think it's necessary to include the scheduler in the report name. The ScheduleType already uniquely identifies the report, and the scheduler is generally a long string (which is not used anywhere else) and we end up with a long unreadable report name.

2019-08-19 22:06 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +        List<StudyParticipant> participants = bridgeHelper.getParticipantsForStudy(studyId, startDate, endDate);
I agree with Alx here. Fortunately, we have an AccountSummaryIterator that does exactly what you want https://github.com/Sage-Bionetworks/BridgeWorkerPlatform/blob/develop/src/main/java/org/sagebionetworks/bridge/notification/helper/BridgeHelper.java#L38 Note that this lives in the Notification Worker's BridgeHelper, so you'll need to copy it into the Reporter's BridgeHelper. (We have a task to refactor all the BridgeHelpers into a single BridgeHelper.

Once you have an iterator of Account Summaries, you can then load the Study Participant, Request Info, and Activity Events by User ID.

2019-08-27 17:25 UTC, janaechan commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +    	    			int days = Days.daysBetween(entry.getValue().getItems().get(i).getTimestamp().toDateTime().toLocalDate(), entry.getKey().getUploadedOn().toLocalDate()).getDays();
Eclipse isn't applying the max line width setting, so I might need to go in and shorten lines manually

2019-08-27 17:28 UTC, janaechan commented
Should I add a before() method with the annotation @BeforeMethod in BridgeHelperTest to set up the ForWorkerApi, ClientManager, and BridgeHelper to remove some redundancy?

2019-08-27 22:27 UTC, DwayneJengSage reviewed
> Should I add a before() method with the annotation @BeforeMethod in BridgeHelperTest to set up the ForWorkerApi, ClientManager, and BridgeHelper to remove some redundancy?

I would recommend doing so, yes. Removing repeated code makes maintaining and updating easier.

2019-08-27 22:27 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/helper/BridgeHelper.java
> +    }
Did you have to make a change to AccountSummaryIterator to get this to work?

2019-08-27 22:27 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +            DateTime studyStartDate = studyParticipant.getCreatedOn();
If we always re-calculate study_start_date on the server-side, do we still need to fetch the Participant to get the createdOn?

2019-08-27 22:27 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +            AccountSummary accountSummary = accountSummaryIter.next();
I'd recommend wrapping the inside of the loop in a try-catch block. Otherwise, if a single participant has an error, the whole report errors out.

Secondly, I'd recommend using a RateLimiter of some sort to limit how many requests you are sending at once. There are 250k accounts in prod right now, so if we RateLimit to 100 accounts per second, we'll finish the report in 45 minutes. (Currently discussing with Alx about whether we should use a whitelist to only run this report on selected studies, but that would happen in the scheduler, not the worker.)

Similarly, we should increase the page_size in AccountSummaryIterator to 100, which is the max.

2019-08-27 22:55 UTC, janaechan commented on src/main/java/org/sagebionetworks/bridge/reporter/helper/BridgeHelper.java
> +    }
No changes were made to the code. I created a AccountSummaryIterator (copied from notification.helper) in reporter.helper but this call to AccountSummaryIterator still routes to the notification.helper iterator.

2019-08-27 23:33 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/reporter/helper/BridgeHelper.java
> +    }
Doesn't the one from notification.helper only show accounts with phone numbers?

2019-08-27 23:53 UTC, DwayneJengSage requested changes

2019-08-27 23:53 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/reporter/helper/BridgeHelperTest.java
> +        assertEquals(activityEventList.getItems(), mockActiviyEventList.getItems());
You might want to try assertSame() to verify the activityEventList you're getting from the workerApi is the same activityEventList being returned by the BridgeHelper. Right here, you're just comparing null to null. (assertSame() might also be better for the other tests as well.)

2019-08-27 23:53 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGeneratorTest.java
> +public class RetentionReportGeneratorTest {
Maybe add a test with two or three users to make sure the report is being aggregated correctly.

2019-08-28 15:14 UTC, janaechan commented on src/main/java/org/sagebionetworks/bridge/reporter/helper/BridgeHelper.java
> +    }
Oh right! I forgot I made that change, thanks for remembering!

2019-08-29 19:25 UTC, janaechan commented on src/main/java/org/sagebionetworks/bridge/reporter/worker/RetentionReportGenerator.java
> +        String reportId = scheduler + scheduleType.getSuffix();
getSuffix() is only used when generating reports. Can I remove the leading "-" of getSuffix() and remove the scheduler from from the report name?

2019-08-30 07:34 UTC, DwayneJengSage requested changes
Looks good. Just one comment on the assert.

Similar to Server2, you should run `mvn verify` on this. Also, you should run `mvn spring-boot:run` on both Server2 and Worker and run your updated WorkerTest against your Worker. (Note that FitBitWorker will fail. That's expected, as that requires a lot of specific setup. The reporter tests should work though.)

2019-08-30 07:34 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/reporter/helper/BridgeHelperTest.java
> +        assertSame(activityEventList.getItems(), mockActiviyEventList.getItems());
You should call assertSame on the activityEventList itself. Otherwise, you're comparing null to null, which is trivially true.

2019-08-30 19:06 UTC, DwayneJengSage requested changes
Aren't we also pulling in a new API for getRequestInfo? There should be an update to pom.xml as well.

2019-08-31 00:10 UTC, DwayneJengSage reviewed
Looks good. Looks like there's a merge conflict you need to resolve.

Also, do we have changes for BridgeWorkerIntegrationTests?

2019-09-03 18:04 UTC, DwayneJengSage approved these changes

2019-09-03 18:18 UTC, merged